spring:
  application:
    name: missing-tc-notification-workflow
  profiles:
    active: ${PROFILE}

server:
  port: 8080
  servlet:
    context-path: /missing-tc-notification-workflow

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [traceId=%X{traceId}] %logger{1} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true