spring:
  application:
    name: missing-tc-notification-workflow
  cloud:
    gcp:
      project-id: ${GCP-PROJECT-ID:jswone-prod-service}

  temporal:
    connection:
      target: ${MISSING_TC_NOTIFICATION_WORKFLOW_BASE_URL}
    namespace: ${MISSING_TC_NOTIFICATION_WORKFLOW_NAMESPACE}
    workers:
      - task-queue: ${MISSING_TC_NOTIFICATION_WORKFLOW_TASK_QUEUE:missing-tc-notification-queue}
    workers-auto-discovery:
      packages:
        - com.jswone.missing_tc_notification_workflow.jobs.missingTcNotification.workflow
        - com.jswone.missing_tc_notification_workflow.jobs.missingTcNotification.activity

external-service:
  services:
    joms:
      base-url: ${JOMS_BASE_URL}
      api-key: ${JOMS_API_KEY}

temporal:
  missing-tc-notification:
    task-queue: ${MISSING_TC_NOTIFICATION_WORKFLOW_TASK_QUEUE:missing-tc-notification-queue}
    # schedule
    schedule-id: ${MISSING_TC_NOTIFICATION_WORKFLOW_SCHEDULE_ID:missing-tc-notification-daily-schedule}
    schedule-timezone: ${MISSING_TC_NOTIFICATION_WORKFLOW_SCHEDULE_TZ:Asia/Kolkata}
    schedule-hour: ${MISSING_TC_NOTIFICATION_WORKFLOW_SCHEDULE_HOUR:8}
    schedule-minute: ${MISSING_TC_NOTIFICATION_WORKFLOW_SCHEDULE_MINUTE:0}

security:
  api-key: ${MISSING_TC_NOTIFICATION_WORKFLOW-API-KEY}